export const LOAD_PAGE = "LOAD_PAGE";
export const ADD_PAGE = "ADD_PAGE";
export const REMOVE_PAGE = "REMOVE_PAGE";
export const RENAME_PAGE = "RENAME_PAGE";
export const UPLOAD_PAGE = "UPLOAD_PAGE";
export const SHOW_PREVIEW = "SHOW_PREVIEW";
export const HIDE_PREVIEW = "HIDE_PREVIEW";

export const SHOW_MESSAGE = "SHOW_MESSAGE";

export const SHOW_ELEMENT_FRAME = "SHOW_ELEMENT_FRAME";
export const SHOW_RULE_FRAME = "SHOW_RULE_FRAME";
export const SHOW_HTML_FRAME = "SHOW_HTML_FRAME";
export const SHOW_PARTS_FRAME = "SHOW_PARTS_FRAME";
export const SHOW_SPEC_FRAME = "SHOW_SPEC_FRAME";

export const CLOSE_FORAGER = "CLOSE_FORAGER";
export const SHOW_FORAGER = "SHOW_FORAGER";

export const SELECT_ELEMENT = "SELECT_ELEMENT";
export const SAVE_ELEMENT = "SAVE_ELEMENT";
export const REMOVE_ELEMENT = "REMOVE_ELEMENT";
export const RENAME_ELEMENT = "RENAME_ELEMENT";
export const SAVE_RULE = "SAVE_RULE";
export const REMOVE_RULE = "REMOVE_RULE";
export const TOGGLE_OPTIONAL = "TOGGLE_OPTIONAL";
