export const LOAD_PAGE = "LOAD_PAGE";
export const ADD_PAGE = "ADD_PAGE";
export const REMOVE_PAGE = "REMOVE_PAGE";
export const RENAME_PAGE = "RENAME_PAGE";
export const UPLOAD_PAGE = "UPLOAD_PAGE";
export const SHOW_PREVIEW = "SHOW_PREVIEW";
export const HIDE_PREVIEW = "HIDE_PREVIEW";

export const SHOW_SELECTOR_FRAME = "SHOW_SELECTOR_FRAME";
export const SHOW_RULE_FRAME = "SHOW_RULE_FRAME";
export const SHOW_ELEMENT_FRAME = "SHOW_ELEMENT_FRAME";
export const SHOW_PARTS_FRAME = "SHOW_PARTS_FRAME";
export const SHOW_SPEC_FRAME = "SHOW_SPEC_FRAME";

export const CLOSE_FORAGER = "CLOSE_FORAGER";
export const SHOW_FORAGER = "SHOW_FORAGER";

export const SELECT_SELECTOR = "SELECT_SELECTOR";
export const SAVE_SELECTOR = "SAVE_SELECTOR";
export const REMOVE_SELECTOR = "REMOVE_SELECTOR";
export const RENAME_SELECTOR = "RENAME_SELECTOR";
export const SAVE_RULE = "SAVE_RULE";
export const REMOVE_RULE = "REMOVE_RULE";
